/** Mapa emoji → descrição em português para uso como tooltip */
const nomes: Record<string, string> = {
  '😂': 'Chorando de rir',
  '❤️': 'Coração',
  '😍': 'Olhos de coração',
  '🤣': 'Rolando de rir',
  '😊': 'Sorriso tímido',
  '🙏': 'Mãos juntas',
  '😭': 'Chorando muito',
  '😘': 'Mandando beijo',
  '👍': 'Joinha',
  '😅': 'Sorriso com suor',
  '🔥': 'Fogo',
  '🥰': 'Sorriso com corações',
  '😎': 'Óculos de sol',
  '💕': 'Dois corações',
  '🎉': 'Festa',
  '✨': 'Brilhos',
  '😀': 'Sorriso',
  '😃': 'Sorriso com olhos grandes',
  '😄': 'Sorriso largo',
  '😁': 'Sorriso com dentes',
  '😆': 'Rindo apertado',
  '🥹': 'Segurando lágrimas',
  '😋': 'Delícia',
  '😛': 'Mostrando a língua',
  '😜': 'Piscando com língua',
  '🤪': 'Maluco',
  '😝': 'Língua de fora',
  '🤗': 'Abraço',
  '🤭': 'Risinho',
  '🫢': 'Boca aberta com mão',
  '🤫': 'Silêncio',
  '🤔': 'Pensando',
  '🫡': 'Continência',
  '🤐': 'Boca fechada',
  '🤨': 'Sobrancelha levantada',
  '😐': 'Sem expressão',
  '😑': 'Inexpressivo',
  '😶': 'Sem boca',
  '🫠': 'Derretendo',
  '😏': 'Sorriso de lado',
  '😒': 'Entediado',
  '🙄': 'Revirando os olhos',
  '😬': 'Careta',
  '😮‍💨': 'Suspiro',
  '🤥': 'Mentiroso',
  '😌': 'Aliviado',
  '😔': 'Triste',
  '😪': 'Sonolento',
  '🤤': 'Babando',
  '😴': 'Dormindo',
  '😷': 'De máscara',
  '🤒': 'Com termômetro',
  '🤕': 'Com curativo',
  '🤢': 'Enjoado',
  '🤮': 'Vomitando',
  '🥵': 'Calor',
  '🥶': 'Frio',
  '🥴': 'Tonto',
  '😵': 'Zonzo',
  '🤯': 'Mente explodindo',
  '😱': 'Gritando de medo',
  '😨': 'Assustado',
  '😰': 'Ansioso',
  '😢': 'Chorando',
  '😮': 'Surpreso',
  '👏': 'Palmas',
  '👋': 'Acenando',
  '🤚': 'Mão levantada',
  '🖐️': 'Mão aberta',
  '✋': 'Pare',
  '🖖': 'Saudação Vulcana',
  '🫱': 'Mão para direita',
  '🫲': 'Mão para esquerda',
  '👌': 'OK',
  '🤌': 'Gesto italiano',
  '🤏': 'Beliscando',
  '✌️': 'Paz',
  '🤞': 'Dedos cruzados',
  '🫰': 'Mão com dedo indicador',
  '🤟': 'Te amo',
  '🤘': 'Rock',
  '🤙': 'Me liga',
  '👈': 'Apontando esquerda',
  '👉': 'Apontando direita',
  '👆': 'Apontando cima',
  '👇': 'Apontando baixo',
  '☝️': 'Indicador para cima',
  '👎': 'Não curti',
  '✊': 'Punho',
  '👊': 'Soco',
  '🤛': 'Soco esquerdo',
  '🤜': 'Soco direito',
  '🙌': 'Mãos para cima',
  '🫶': 'Coração com mãos',
  '👐': 'Mãos abertas',
  '🤲': 'Palmas juntas',
  '🤝': 'Aperto de mão',
  '💪': 'Músculo',
  '🫂': 'Abraçando',
  '💯': 'Cem pontos',
  '💢': 'Raiva',
  '💬': 'Balão de fala',
  '👁️‍🗨️': 'Olho com balão',
  '🗨️': 'Balão de fala esquerdo',
  '💭': 'Balão de pensamento',
  '💤': 'Dormindo',
  '🎵': 'Nota musical',
  '🎶': 'Notas musicais',
  '❤️‍🔥': 'Coração em chamas',
  '💔': 'Coração partido',
  '💖': 'Coração brilhante',
  '💗': 'Coração crescendo',
  '💙': 'Coração azul',
  '💚': 'Coração verde',
  '💛': 'Coração amarelo',
  '🧡': 'Coração laranja',
  '💜': 'Coração roxo',
  '🖤': 'Coração preto',
  '🤍': 'Coração branco',
  '🤎': 'Coração marrom',
  '⭐': 'Estrela',
  '🌟': 'Estrela brilhante',
  '💫': 'Tontura',
  '🎈': 'Balão',
  '🎊': 'Confete',
  '🎁': 'Presente',
  '🏆': 'Troféu',
  '⚽': 'Futebol',
  '🎮': 'Controle de videogame',
  '📱': 'Celular',
  '💻': 'Notebook',
  '📷': 'Câmera',
  '🎬': 'Claquete',
  '🎤': 'Microfone',
  '🎧': 'Fones de ouvido',
}

export function emojiNome(emoji: string): string {
  return nomes[emoji] || emoji
}
